# When this workflow is triggered the repository is published as a Python package on PyPI.

name: Publish to PyPI

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish_to_pypi:
    runs-on: ubuntu-latest
    if: startsWith( ${GITHUB_REF#refs/*/} , "deepvoxnet2-" )
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ env.RELEASE_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools twine

      - name: Build and upload package
        run: |
          python setup.py sdist
          python -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
