# When this workflow is triggered the repository is published as a Docker container on DockerHub.

name: Publish to DockerHub

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 120 seconds
        run: sleep 120s
        shell: bash

      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "PYPI_VERSION=${GITHUB_REF#refs/*/deepvoxnet2-}" >> $GITHUB_ENV

      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ env.RELEASE_VERSION }}

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_API_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: jeroenbertels/deepvoxnet2

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          build-args: |
            DEEPVOXNET2_VERSION=${{ env.PYPI_VERSION }}

          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
